<?php
/**
 * @file
 */

// Drupal needs this blank file.
include_once('reach_media.features.inc');

/**
 * Implements hook_menu_alter().
 */
function reach_media_menu_alter(&$items) {
  $items['media/%file']['page callback'] = 'reach_media_view_page';
}



/**
 * Menu callback; view a single file entity.
 * Copied from media.module, changed display from media_original to media_large.
 */
function reach_media_view_page($file) {
  // @todo Implement granular editorial access: http://drupal.org/node/696970.
  //   In the meantime, protect information about private files from being
  //   discovered by unprivileged users. File IDs are autoincrement, so one can
  //   attempt discovery by trying to access different media/ID paths. See also
  //   media_browser_list(). This logic potentially belongs within
  //   media_access(), but that would require extending that function's
  //   signature to accept a $file paramter, and this is temporary code anyway.
  //if (!user_access('administer media') && (file_uri_scheme($file->uri) === 'private')) {
  //  return MENU_ACCESS_DENIED;
  //}

  drupal_set_title($file->filename);
  return file_view($file, 'media_page');
}



/**
 * Implements hook_ds_fields_info().
 */
function reach_media_ds_fields_info($entity_type) {
  $fields = array();
  
  if ($entity_type == 'node') { // && module_exists('views_galleria_slideshow')
    $fields[$entity_type]['reach_media_galleria_slideshow'] = array(
      'title' => t('Views Galleria Slideshow'),
      'field_type' => DS_FIELD_TYPE_FUNCTION,
      'function' => 'reach_media_reach_media_galleria_slideshow_view',
      'properties' => array(
        'settings' => array(
          'view_name' => array('type' => 'textfield'),
          'view_display' => array('type' => 'textfield'),
        ),
        'default' => array(
          'view_name' => 'galleria_slideshow',
          'view_display' => 'default',
        ),
      ),
    );
  }
  
  return $fields;
}

/**
 * Implements hook_ds_field_settings_form().
 */
function reach_media_ds_field_settings_form($field) {
  // Saved formatter settings are on $field['formatter_settings'];
  $settings = isset($field['formatter_settings']) ? $field['formatter_settings'] : $field['properties']['default'];

  $form['view_name'] = array(
    '#type' => 'textfield', 
    '#title' => t('View name'), 
    '#default_value' => $settings['view_name'],
    '#width' => 10,
    '#description' => t('This block will automatically pass the media_gallery node as the first argument to the view.'),
  );
  $form['view_display'] = array(
    '#type' => 'textfield', 
    '#title' => t('View display'), 
    '#default_value' => $settings['view_display'],
    '#width' => 10,
  );
  return $form;
}



/**
 * Generates the output for the display suite field.
 */
function reach_media_reach_media_galleria_slideshow_view($field) {
  $settings = isset($field['formatter_settings']) ? $field['formatter_settings'] : $field['properties']['default'];
  return views_embed_view($settings['view_name'], $settings['view_display'], $field['entity']->nid);
}

/**
 * Implements hook_views_pre_render.
 */
function reach_media_views_pre_render(&$view) {
  if ($view->name == 'galleria_slideshow') {
    drupal_add_js(drupal_get_path('module', 'reach_media') . '/js/watcher.js');
    drupal_add_js(drupal_get_path('module', 'reach_media') . '/js/reach-media-responsive-galleria.js');
  }
}


/**
 * Implements hook_form_alter.
 */
function reach_media_form_media_internet_add_alter(&$form, &$form_state, $form_id) {
  $form['embed_code']['#description'] = t('Enter the URL of the media resource you would like to embed.  
    Supported providers include Youtube, Vimeo, Flickr, Digg, SoundCloud, and many more.  For a full list, go to !embedly',
    array('!embedly' => l('embed.ly/providers', 'http://embed.ly/providers', array('attributes' => array('target' => '_blank')) )));
  unset($form['providers']);
}

/**
 * Implements hook_form_alter.
 */
function reach_media_form_media_gallery_node_form_alter(&$form, &$form_state, $form_id) {
  //if (!$form['nid']['#value']) {
    $form['media_gallery_format'][LANGUAGE_NONE]['#default_value'] = 'node';
    $form['media_gallery_format'][LANGUAGE_NONE]['#type'] = 'hidden';
  //}
  
}



